---
title: "Project"
author: "Shivam Tiwari"
date: "May 6, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(C50)
library(ggplot2)
library(maps)
library(caret)
library(plyr)
library(scales)
library(pROC)
library(ROCR)
library(caret)
```
```{r}
data(churn)
#Question 1

#The data contains following information about the customer
#1.	The State and the area code of the customer
#2.	The duration of customer's account with the company (account length) (most probably in weeks)
#3.	Whether the customer has taken an international plan and voice mail plan or not (one column for each)
#4.	The number of voice mail messages the customer has received
#5.	Total minutes, total calls and total amount incurred for each customer overall in the day, evening and night (one column for each)
#6. Total minutes, calls and total amount incurred for each customer in the international calls
#7. Total number of customer service calls customer has made to the company
#8. Whether the customer churned or not



fullset <- rbind(churnTest, churnTrain)
ch_tot <- sum(fullset$churn == 'yes')
ch_rate <- (ch_tot/nrow(fullset))*100
ch_rate
#Overall Churn rate of the company (including both training and test data) is 14.14%


for (i in 1:nrow(churnTrain)){
  churnTrain$ovrcharge[i] <- sum(churnTrain$total_day_charge[i], churnTrain$total_eve_charge[i],churnTrain$total_night_charge[i],churnTrain$total_intl_charge[i])
}
state_ovr<- aggregate(churnTrain$ovrcharge, by= list(churnTrain$state), FUN = 'sum')
#US Map for total revenue by state
states <- map_data('state')
state_ovr$x <- state_ovr$x/1000
state_ovr$region <- state.name[match(state_ovr$Group.1,state.abb)]
f<- c("region", "x")
usplot <- state_ovr[f]
uss <- na.omit(usplot)
uss$x <- round(uss$x, 2)
uss$region <- tolower(uss$region)
sim_dg <- merge(states,uss, by= 'region')
snames <- data.frame(region=tolower(state.name), long=state.center$x, lat=state.center$y)
snames <- merge(snames, uss, by='region')
ggplot(sim_dg, aes(long, lat)) + geom_polygon(aes(group=group, fill=x)) + geom_text(data=snames, aes(long, lat, label=x)) + ggtitle("Total Revenue by state - 1 unit represents $1000")

#US Map for total subscribers by state
subs <- count(churnTrain$state)
subs$x <- state.name[match(subs$x,state.abb)]
subs <- na.omit(subs)
subs$x <- tolower(subs$x)
subs$region <- subs$x
subs <- subs[,-1]
sub_dg <- merge(states,subs, by= 'region')
snames1 <- data.frame(region=tolower(state.name), long=state.center$x, lat=state.center$y)
snames1 <- merge(snames1, subs, by='region')
ggplot(sub_dg, aes(long, lat)) + geom_polygon(aes(group=group, fill=freq)) + geom_text(data=snames1, aes(long, lat, label=freq)) + ggtitle("Number of Subscribers in each state")


#Pie Chart for total revenue by time (day, evening and night)
day <- sum(churnTrain$total_day_charge)
eve <- sum(churnTrain$total_eve_charge)
night <- sum(churnTrain$total_night_charge)
all<- cbind(day,eve,night)
all <- data.frame(t(all))
all$time <- c('day','eve','night')
ggplot(data = all, aes(x = "", y =t.all., fill = time)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = t.all.), position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y") + ggtitle("Total revenue by time") +
  labs(x="",y="") 


#Question 2

#For Interpretable model, we use Logit model

#Logit
#checking and removing correlations
churnt <- churnTrain[,-c(1,3,4,5,20,21)]
churnt <- churnt[,-16]
df <- cor(churnt, method = 'pearson')
trainset <- churnTrain[,-c(7,10,13,16,21,22,23)]


#We remove state and area code from the model because they would not contribute to any strategy that we aim to device for retaining customers
logittrain <- train(x=trainset[,-c(1,3,16,17)], y=trainset$churn, method = 'glm', family = binomial)
summary(logittrain)
logitpredict <- predict(logittrain, churnTest)
confusionMatrix(logitpredict,churnTest$churn)
#Though there was class imbalance, but in our case, a False Positive rate would hurt us more - as we would say that a customer is not churning, but in actual it would.
#Here our specificity is high, so there seems to be no problem
cal_roc <- roc(as.numeric(logitpredict), as.numeric(churnTest$churn))
#Area under curve
auc(cal_roc)
#ROC plot
plot(cal_roc)

#We see there are some significant variables that contribute to churn. Most important of them are:
#1.	Those who have taken international plan
#2.	Those who have taken a voice mail plan
#3.	Total charge incurred by a customer in the day
#4.	Total charge incurred by a customer in the evening
#5.	Total charge incurred by a customer in the night
#6.	Total International Calls made by each customer
#7.	Total charge incurred on international calls
#8.	Total number of customer service calls 
#9. Total number of voice mail messages

#Looking at the estimates, it seems that if a customer incurs more charge at the day, evening or night, or if he/she takes our international plan
#he/she is more likely to stay with the customer - This shows that those customers are LOYAL customers and are happy with our services
#However, if the International Calls (not charge) of a customer are more, he or she is likely to churn. Maybe then the customer calls and incurs more charge but finds the rates unreasonable or high (as the customer might have taken international plan as well - cause it is also a significant variable)
#This suggests that IF we reduce the International rates, we will have a better chance to retain the customer
#Also, more the number of voice mail messages, more likely the customer is to churn. This means that the customer has taken voice mail plan but does not use it. So, he/she might feel that the plan is going waste.
#So, we can ask those specific customers to deactivate the voice mail plan and increase the chance of retaining them.
#We come up with 2 strategies here -
#1. Decrease International call price
#2. Request those customers who have many voice mails to deactivate the plan 



#Question 3

#Random Forest was chosen after running models of Decision trees, Random Forests and XGBoost
#Random Forest model is provided below


red<- churnTrain
red <- red[,-c(7,10,13,16,20,21,22,23)]
indx <- createFolds(churnTrain$churn, returnTrain = TRUE)
ctrl <- trainControl(method = "cv",summaryFunction = twoClassSummary, index = indx,classProbs = TRUE, savePredictions = TRUE)
mtryValues <- c(1:5)
set.seed(714)
rfCART <- train(red, churnTrain$churn,
                method = "rf",
                metric = "Kappa",
                ntree = 1000,
                importance = TRUE,
                tuneGrid = data.frame(.mtry = mtryValues),
                trControl = ctrl)
summary(rfCART)
rfp <- predict(rfCART,churnTest)
tr <-confusionMatrix(rfp, churnTest$churn)
tr
roc_rf <- roc(as.numeric(rfp), sapply(churnTest$churn,as.numeric))
plot(roc_rf)
auc(roc_rf)
varImp(rfCART)
plot(varImp(rfCART))


```

